### ISSUE TITLE
Irrelevant license in readme & trouble with installing via pip

### ISSUE THREAD

**Issue by vonafor** [sqreen/AioContext#2]
I think you've forgot to update it.
> AioContext is released under the **LGPL** license, its documentation lives at Read the Docs and the code on GitHub.

Another issue. Seems there is no package in PyPI. I cannot install it with command `pip install aiocontext`

**Comment by vivienm** [comment]
Good catch, thanks!

**Comment by vivienm** [comment]
Hi @vonafor, thank you for reporting these issues! We've updated the README and published the package on PyPI.
